### ISSUE TITLE
请问大佬的其他场景文件是在哪里找的，我用pbrt的场景文件解析不了，小白不太懂。。

### ISSUE THREAD

**Issue by qaz123w** [cuteday/KiRaRay#19]
打算看大佬的这个项目学OptiX7。

**Comment by cuteday** [comment]
你好
这边是用了pbrt-parser这个库读pbrt的场景，它只支持v3的格式。[这里](https://benedikt-bitterli.me/resources/)不少场景能读，但是需要手动把下载链接改成v3，比如https://benedikt-bitterli.me/resources/pbrt-v3/kitchen.zip，然后config里路径指向场景的.pbrt文件就行。不过我这个pbrt读入写得相当粗糙，所以也有很多场景读不进来，像是官方示例场景好像就不太行？之后有空的话我会再看看为啥不行。

P.S. 有人能发现这个项目我是很开心了，但是如果照这个学的话可能不是很好的选择，因为作者也是小白(现在也是新手)。这个有很多突出的问题，比如说代码东拼西凑(主要参考的是Falcor和pbrt-v4)，命名混乱和c++写法差。比较推荐照着真·大佬的学(比如[这个](https://github.com/shocker-0x15/VLR/tree/master/libVLR))，当然我这个参考一下还是可以的，毕竟代码结构比那些简单一些。

**Comment by qaz123w** [comment]
谢谢

**Comment by qaz123w** [comment]
大佬考虑在博客上写教程吗

**Comment by qaz123w** [comment]
太感谢了
